coverage_server:
  ros__parameters:
    action_server_result_timeout: 10.0
    coordinates_in_cartesion_frame: True
    robot_width: 2.1
    operation_width: 2.5
    min_turning_radius: 0.4
    linear_curv_change: 2.0
    default_allow_overlap: false
    default_headland_type: "CONSTANT"
    default_headland_width: 2.0
    default_swath_type: "LENGTH"
    default_swath_angle_type: 1.7e-2
    default_step_angle: 1.7e-2  
    default_route_type: "BOUSTROPHEDON"   
    default_spiral_n: 4
    default_path_type: "CONTINUOUS"
    default_turn_point_distance: "DUBIN"
    default_offset: 0.0


