map_server:
  ros__parameters:
    yaml_filename: 'gallery.yaml'
    topic_name: "map"
    frame_id: "map"

map_saver:
  ros_parameters:
    save_map_timeout: 2.0
    free_tresh_default: 0.25
    occupied_tresh_default: 0.65

costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "costmap_filter_info"
    mask_topic: "filter_mask"
    base: 0.0
    multiplier: 1.0

    