planner_server:
  ros__parameters:
    expected_planner_frequency: [20.0]
    action_server_result_timeout: 10.0
    planner_plugins: ['GridBased']
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

      