smoother_server:
  ros__parameters:
    costmap_topic: "global_costmap/costmap_raw"
    footprint_topic: "global_costmap/published_footprint"
    action_server_result_timeout: 10.0
    transform_tolerance: 0.1
    robot_base_frame: "base_link"
    transform_timeout: 0.1
    smoother_plugins: ["simple_smoother"]   
    simple_smoother:
      plugin:
      tolerance:
      do_refinement:

      