waypoint_follower:
  ros_parameters:
    loop_rate: 20
    stop_on_failure: True
    action_server_result_timeout: 900.0
    global_frame_id: 'map'
    waypoint_task_executor_plugin: "wait_at_waypoint"
      wait_at_waypoint:
        plugin: "nav2_waypoint_follower::WaitAtWaypoint"
        enabled: True
        waypoint_pause_duration: 0
      